# Generated by Django 4.0.3 on 2022-04-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isSeller',
            new_name='is_seller',
        ),
    ]
